global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using CandleShop.Services.Catalog.API.Infrastructure;
global using CandleShop.Services.Catalog.API.Infrastructure.EntityConfigurations;
global using CandleShop.Services.Catalog.API.Model;
global using CandleShop.Services.Catalog.API.Model.Dto;
global using CandleShop.Services.Catalog.API.ViewModel;
global using System.Net;